"""Add status, payment_progress, and cost to Task

Revision ID: 0aba0d9ecfbf
Revises: 
Create Date: 2024-07-10 19:33:43.150206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aba0d9ecfbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_progress', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('payment_progress')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
